### ISSUE TITLE
PyJWT 2 breaks _create_token function

### ISSUE THREAD

**Issue by mvanbaak** [genesluder/python-apns#28]
PyJWT has released version 2.0.0 (and newer versions), removing python2 and python < 3.6 compatibily.
This means the jwt.encode() function now returns a string. string type in python3 has no .decode() method.

This can be fixed 2 ways:

* add <2 to the pyjwt in setup.py install_requires
* fix the code to not run .decode() on the created jwt

**Comment by genesluder** [comment]
Merged and distributed to pypi in 0.1.6. Thanks!
